name: Check lint

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - '!main'  # Lint for main branch is done in release.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with: { run_install: false }

      - uses: actions/setup-node@v4
        with: { node-version: latest, cache: 'pnpm' }

      - run: pnpm install

      - run: pnpm run lint
