name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      WORKFLOW_PHASE:
        description: 'Deployment phase'
        required: true
        default: stage
        type: choice
        options: [ stage, prod ]
  push:
    branches: [ main ]

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  build-storybook:
    runs-on: ubuntu-latest
    needs: [ lint ]
    permissions:
      contents: read
      pages: write
      id-token: write
    env:
      RELEASE_TYPE: ${{ github.event_name == 'workflow_dispatch' && inputs.WORKFLOW_PHASE || 'stage' }}

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: pnpm/action-setup@v4
        with: { run_install: false }

      - uses: actions/setup-node@v4
        with: { node-version: latest, cache: 'pnpm' }

      - run: pnpm install

      - run: pnpm run build-storybook

      - uses: actions/configure-pages@v5

      - uses: actions/upload-pages-artifact@v3
        with: { path: 'storybook-static' }

      - uses: actions/deploy-pages@v4
        with: { preview: "${{ env.RELEASE_TYPE == 'stage' }}" }

  # build-package:
  #   runs-on: ubuntu-latest
  #   needs: [ lint ]
  #   permissions:
  #     contents: read
  #     packages: write
  #   env:
  #     RELEASE_TYPE: ${{ github.event_name == 'workflow_dispatch' && inputs.WORKFLOW_PHASE || 'stage' }}

  #   steps:
  #     - uses: actions/checkout@v4
  #       with: { fetch-depth: 0 }

  #     - uses: pnpm/action-setup@v4
  #       with: { run_install: false }

  #     - uses: actions/setup-node@v4
  #       with: { node-version: latest, cache: 'pnpm' }

  #     - run: pnpm install

  #     - run: pnpm run build

  #     - run: pnpm publish
